version: '3.8'

services:
  grafana:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: grafana
    environment:
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=
      - GF_SMTP_USER=
      - GF_SMTP_PASSWORD=
      - GF_SMTP_SKIP_VERIFY=true
      - GF_SMTP_FROM_ADDRESS=

    ports:
      - "3000:3000"

