version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: grafana
      POSTGRES_USER: grafana
      POSTGRES_PASSWORD: grafana_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  grafana:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: grafana
    environment:
      - GF_DATABASE_TYPE=postgres
      - GF_DATABASE_HOST=postgres:5432
      - GF_DATABASE_NAME=grafana
      - GF_DATABASE_USER=grafana
      - GF_DATABASE_PASSWORD=grafana_password
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=
      - GF_SMTP_USER=
      - GF_SMTP_PASSWORD=
      - GF_SMTP_SKIP_VERIFY=true
      - GF_SMTP_FROM_ADDRESS=

    depends_on:
      - postgres
    ports:
      - "3000:3000"

volumes:
  postgres_data:
